name: cinemapedia
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^13.2.5
  flutter_dotenv: ^5.1.0
  flutter_riverpod: ^2.5.1
  dio: ^5.4.3+1
  card_swiper: ^3.0.1
  animate_do: ^3.3.4
  intl: ^0.19.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
